[package]
name = "jack-delay"
version = "0.1.0"
authors = ["DanielMowitz <dmowitz@students.uni-mainz.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jack = "0.7"
structopt = "0.3"
